[Methods]
method : mcts
action : simpleactions
sensor : drone
state : rfstate
target_speed: 1.0
target_start: 100
resample_proportion: 0.005
#target_speed_range: [0,1,2,3,4]

[Defaults]
lambda_arg : 0.8
collision : -2.
loss : -2.
depth : 10
simulations : 200
plotting : False
trials : 500
iterations : 150
